Remove unused cli arg tanssi_experimental_max_pov_percentage (#1178)
It's not used and causes some very weird error messages

error: invalid value 'a' for '[tanssi_experimental_max_pov_percentage]': invalid digit found in string