Install locked twiggy version (#1015)
error: failed to compile twiggy v0.7.0
Caused by:
rustc 1.81.0 is not supported by the following package:
backtrace@0.3.75 requires rustc 1.82.0